import './global.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import { ReactNode } from 'react';
import FooterWrapper from '../components/sections/layouts/footerWrapper';
import { SocialMediaConnect } from '../components/social-media-connect';

export const metadata = {
  title: 'Welcome to furniture-draw-introduction',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>
          <SocialMediaConnect />
          {children}
        </main>
        <FooterWrapper />
      </body>
    </html>
  );
}
